Les types de base,
Les tableaux et les objets,
Les fonctions,
Unions et types,
Tuple et Enum,
Les Interfaces,
Le DOM,
TSConfigutation,
Les opérateurs,
Overloads,
Generics,
Les classes de base, 
Les champs et le raccourci,
Interfaces et classes.